In [12]:
import numpy as np
import pandas as pd

In [13]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoidGrad(x):
    return x * (1-x)

In [14]:
x = np.array(([2, 9], [1, 5], [3, 6]), dtype = float)
y = np.array(([92], [86], [50]), dtype = float)
# Here np.amax will be [3, 9] if axis = 1 then it will be [9, 5, 6]
# The first col will be divided by 3 and the last col will be divided by 9
# [[0.66666667 1.        ]
#  [0.33333333 0.55555556]
#  [1.         0.66666667]]
X = x/np.amax(x, axis = 0)
Y = y/100
print(X)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]


In [15]:
epoch = 7000
lr = 0.1

ineuron = 2
hneuron = 3
oneuron = 1
# Input layer and input layer bias
hLayer = np.random.uniform(size = (2, 3))
hBias = np.random.uniform(size = (1, 3))
# Ouput layer and output layer bias
oLayer = np.random.uniform(size = (3, 1))
oBias = np.random.uniform(size = (1, 1))
print(inputLayer)

[[-2.63334747  0.90502355 -2.41973234]
 [ 2.36128827 -0.08188098  2.05395094]]


In [19]:
for i in range(epoch):
    # input layer 2 * 3 and X is 3 * 2 output is 3 * 3
    # each row is added to each row
    hInput = np.dot(X, hLayer) + hBias
    hOut = sigmoid(hInput)
    oInput = np.dot(hOut, oLayer) + oBias
    output = sigmoid(oInput)
    
    oError = Y - output 
    
    oGrad = sigmoidGrad(output)
    diffOp = oError * oGrad
    # * is just array multiplication and not matrix multiplication. (dot) is matrix multiplication   
    hiddenError = diffOp.dot(oLayer.T)
    
    hGrad = sigmoidGrad(hOut)
    diffH = hiddenError * hGrad
    
    oLayer += hOut.T.dot(diffOp) * lr
    hLayer += X.T.dot(diffH) * lr

print("Normalized input\n" + str(X))
print("Normalized Output\n" + str(Y))
print("Prediction\n", output)

Normalized input
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Normalized Output
[[0.92]
 [0.86]
 [0.5 ]]
Prediction
 [[0.89058684]
 [0.88795354]
 [0.50230457]]
