In [0]:
from google.colab import files
upload = files.upload()

In [1]:
import pandas as pd
import numpy as np
import string

In [4]:
news = pd.read_csv("news.csv")
# news['CATEGORY'] = news.CATEGORY.map({'b': 1, 't': 2, 'e': 3, 'm': 4})
news.tail(6)
# news = news.replace(np.nan, '', regex = True)
news.tail(6)

ID                                              TITLE  \
422413  422932  Cincinnati Children's surgeons to rebuild thro...   
422414  422933  Surgeons to remove 4-year-old's rib to rebuild...   
422415  422934  Boy to have surgery on esophagus after battery...   
422416  422935  Child who swallowed battery to have reconstruc...   
422417  422936  Phoenix boy undergoes surgery to repair throat...   
422418  422937  Phoenix boy undergoes surgery to repair throat...   

                                                      URL        PUBLISHER  \
422413  http://www.wsmv.com/story/26378648/surgeons-re...   WSMV Nashville   
422414  http://www.cbs3springfield.com/story/26378648/...          WSHM-TV   
422415  http://www.wlwt.com/news/boy-to-have-surgery-o...  WLWT Cincinnati   
422416  http://www.newsnet5.com/news/local-news/child-...     NewsNet5.com   
422417  http://www.wfsb.com/story/26368078/phoenix-boy...             WFSB   
422418  http://www.cbs3springfield.com/story/26368078/...          WSHM-TV   

       CATEGORY                          STORY                 HOSTNAME  \
422413        m  dpcLMoJD69UYMXMxaoEFnWql9YjQM             www.wsmv.com   
422414        m  dpcLMoJD69UYMXMxaoEFnWql9YjQM  www.cbs3springfield.com   
422415        m  dpcLMoJD69UYMXMxaoEFnWql9YjQM             www.wlwt.com   
422416        m  dpcLMoJD69UYMXMxaoEFnWql9YjQM         www.newsnet5.com   
422417        m  dpcLMoJD69UYMXMxaoEFnWql9YjQM             www.wfsb.com   
422418        m  dpcLMoJD69UYMXMxaoEFnWql9YjQM  www.cbs3springfield.com   

            TIMESTAMP  Unnamed: 8  
422413  1409229189743         NaN  
422414  1409229190251         NaN  
422415  1409229190508         NaN  
422416  1409229190771         NaN  
422417  1409229191071         NaN  
422418  1409229191565         NaN

In [0]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(news['TITLE'], news['CATEGORY'], random_state=1)

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words="english")
trainData = cv.fit_transform(xTrain)
testingData = cv.transform(xTest)

In [12]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(trainData, yTrain)
pred = nb.predict(testingData)
pred

array([1, 1, 3, ..., 1, 1, 4])

In [13]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
print(accuracy_score(yTest, pred))
print(classification_report(yTest, pred))
print(confusion_matrix(yTest, pred))

0.9283367264807537
              precision    recall  f1-score   support

           1       0.91      0.91      0.91     29028
           2       0.90      0.91      0.90     27174
           3       0.97      0.96      0.96     38082
           4       0.92      0.92      0.92     11321

    accuracy                           0.93    105605
   macro avg       0.92      0.92      0.92    105605
weighted avg       0.93      0.93      0.93    105605

[[26306  1842   478   402]
 [ 1733 24703   496   242]
 [  547   717 36607   211]
 [  389   187   324 10421]]
